[package]
name = "redox_netstack"
version = "0.1.0"

[[bin]]
name = "ethernetd"
path = "src/ethernetd/main.rs"

[[bin]]
name = "ipd"
path = "src/ipd/main.rs"

[[bin]]
name = "tcpd"
path = "src/tcpd/main.rs"

[[bin]]
name = "udpd"
path = "src/udpd/main.rs"

[[bin]]
name = "icmpd"
path = "src/icmpd/main.rs"

[[bin]]
name = "smolnetd"
path = "src/smolnetd/main.rs"

[dependencies]
netutils = { git = "https://github.com/redox-os/netutils.git" }
rand = "0.3"
redox_event = { git = "https://github.com/redox-os/event.git" }
redox_syscall = "0.1"

[dependencies.log]
version = "0.3"
default-features = false
features = ["release_max_level_off"]

[dependencies.smoltcp]
git = "https://github.com/m-labs/smoltcp.git"
default-features = false
features = ["std", "log"] 
